namespace : egov
# Common Labels
labels:
  app: "inbox"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "inbox"

# Container Configs
image:
  repository: "inbox"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/inbox/health"
  readinessProbePath: "/inbox/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 384Mi
service-map: '{"FSM":{"searchPath":"http://localhost:9098/fsm/v1/_search","dataRoot":"fsm","applNosParam":"applicationNos","businessIdProperty":"applicationNo","applsStatusParam":"applicationStatus"},"FSM_VEHICLE_TRIP":{"searchPath":"http://localhost:8061/vehicle/trip/v1/_search","dataRoot":"vehicleTrip","applNosParam":"applicationNos","businessIdProperty":"applicationNo","applsStatusParam":"applicationStatus"},"PT.CREATE,PT.MUTATION,PT.UPDATE":{"searchPath":"http://localhost:8088/property-services/property/_search","dataRoot":"Properties","applNosParam":"acknowldgementNumber","businessIdProperty":"acknowldgementNumber","applsStatusParam":"status"},"NewTL,EDITRENEWAL,DIRECTRENEWAL":{"searchPath":"http://localhost:8088/tl-services/v1/_search","dataRoot":"Licenses","applNosParam":"applicationNumber","businessIdProperty":"applicationNumber","applsStatusParam":"status"}}'
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKFLOW_PROCESS_SEARCH_PATH
    value: "egov-workflow-v2/egov-wf/process/_search"
  - name: WORKFLOW_BUSINESSSERVICE_SEARCH_PATH
    value: "egov-workflow-v2/egov-wf/businessservice/_search"
  - name: WORKFLOW_PROCESS_COUNT_PATH
    value: "egov-workflow-v2/egov-wf/process/_count"
  - name: WORKFLOW_PROCESS_STATUSCOUNT_PATH
    value: "egov-workflow-v2/egov-wf/process/_statuscount"
  - name: SERVICE_SEARCH_MAPPING
    value:  {{ index .Values "service-map" | quote }} 
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
