# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/egov-production\-secrets\.yaml$
          kms: 'arn:aws:kms:me-central-1:586501623975:key/73698f5a-d655-4991-bd07-ffe139170601'
        - path_regex: environments/ci-production\-secrets\.yaml$
          kms: 'arn:aws:kms:me-central-1:586501623975:key/73698f5a-d655-4991-bd07-ffe139170601'
